In [ ]:
import pandas as pd

df_raw = pd.read_pickle("processed_data/full_dataset_raw.pkl")
#print(len(df_raw))

In [2]:
df_raw.keys()

Index(['Object', 'Time Step', 'Id', 'Label', 'Services', 'Users',
       'Data packets', 'Distribution', 'Scenario', 'App', 'Run', 'User',
       'Application', 'Size', 'Status', 'Queue Delay', 'Transmission Delay',
       'Processing Delay', 'Propagation Delay', 'Total Delay', 'Total Path',
       'Hops', 'Instance ID', 'Coordinates', 'Base Station', 'Delays',
       'Delay SLAs', 'Communication Paths', 'Making Requests',
       'Access History', 'Available', 'CPU', 'RAM', 'Disk', 'CPU Demand',
       'RAM Demand', 'Disk Demand', 'Ongoing Migrations', 'Registries',
       'Layers', 'Images', 'Download Queue', 'Waiting Queue',
       'Max. Concurrent Layer Downloads', 'Power Consumption', 'Server',
       'Being Provisioned', 'Processing Time', 'Processing Output',
       'Last Migration'],
      dtype='str')

In [ ]:
columns_to_keep = [

    'Distribution', 'Scenario', 'App_ms', 'Run', 'Time Step', 'Object', 'Id',

    # DataPacket
    'Status',
    'User',
    'Application',
    'Processing Delay',
    'Propagation Delay',
    'Total Delay',
    'Total Path',
    'Hops',

    # User
    'Delays', 'Delay SLAs',

    # Application
    'Services', 'Users', 'Data packets',

    # Service
    'Server', 'Processing Time'
]

df_light = df_raw[columns_to_keep].copy()

In [ ]:
user_data_SLA = df_light[df_light['Object'].str.contains('User', na=False)].groupby(['Scenario', 'App_ms'])['Delay SLAs'].first().apply(lambda d: list(d.values())[0]).reset_index()
user_data_SLA.head()

           Scenario   App  Delay SLAs
0  1_26_solution_v0  1MMM      70.786
1  1_26_solution_v0  1MMS      70.786
2  1_26_solution_v1  1MMM      77.410
3  1_26_solution_v1  1MMS      77.410
4  1_26_solution_v4  1MMM      66.866

In [ ]:
df_packets = df_light[df_light["Status"] == "finished"].copy()

if 'Delay SLAs' in df_packets.columns:
    df_packets = df_packets.drop(columns=['Delay SLAs'])

df_packets_sla = df_packets.merge(user_data_SLA, on=['Scenario', 'App_ms'], how='left')

columns_to_keep = [

    'Distribution', 'Scenario', 'App_ms', 'Run', 'Time Step', 'Object', 'Id',

    # DataPacket
    'Status',
    'User',
    'Application',
    'Processing Delay',
    'Propagation Delay',
    'Total Delay',
    'Delay SLAs', # aggiunto
    'Total Path',
    'Hops',
]

df_packets_sla = df_packets_sla[columns_to_keep].copy()
#df_packets_sla[df_packets_sla['Scenario'] == '2_26_solution_v9'].head(10)
df_packets_sla

,Distribution,Scenario,App,Run,Time Step,Object,Id,Status,User,Application,Processing Delay,Propagation Delay,Total Delay,Delay SLAs,Total Path,Hops
0,uniform,2_26_solution_v9,2SMS,run_7,38,DataPacket_2,2.0,finished,2.0,2.0,27.0,17.0,44.0,62.258,"[[17], [17], [17], [17, 16], [16, 22], [22], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1,uniform,2_26_solution_v9,2SMS,run_7,39,DataPacket_2,2.0,finished,2.0,2.0,27.0,17.0,44.0,62.258,"[[17], [17], [17], [17, 16], [16, 22], [22], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
2,uniform,2_26_solution_v9,2SMS,run_7,40,DataPacket_2,2.0,finished,2.0,2.0,27.0,17.0,44.0,62.258,"[[17], [17], [17], [17, 16], [16, 22], [22], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
3,uniform,2_26_solution_v9,2SMS,run_7,41,DataPacket_2,2.0,finished,2.0,2.0,27.0,17.0,44.0,62.258,"[[17], [17], [17], [17, 16], [16, 22], [22], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
4,uniform,2_26_solution_v9,2SMS,run_7,42,DataPacket_1,1.0,finished,1.0,1.0,29.0,32.0,61.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,exponential,1_26_solution_v0,1MMS,run_2,34,DataPacket_1,1.0,finished,1.0,1.0,20.0,37.0,57.0,70.786,"[[13], [13], [13, 21, 16], [16, 21, 24, 19], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1228,exponential,1_26_solution_v0,1MMS,run_3,35,DataPacket_1,1.0,finished,1.0,1.0,21.0,37.0,58.0,70.786,"[[13], [13], [13, 21, 16], [16, 21, 24, 19], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1229,exponential,1_26_solution_v0,1MMS,run_0,39,DataPacket_1,1.0,finished,1.0,1.0,25.0,37.0,62.0,70.786,"[[13], [13], [13, 21, 16], [16, 21, 24, 19], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1230,exponential,1_26_solution_v0,1MMS,run_5,29,DataPacket_1,1.0,finished,1.0,1.0,15.0,37.0,52.0,70.786,"[[13], [13], [13, 21, 16], [16, 21, 24, 19], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1231,exponential,1_26_solution_v0,1MMS,run_6,40,DataPacket_1,1.0,finished,1.0,1.0,26.0,37.0,63.0,70.786,"[[13], [13], [13, 21, 16], [16, 21, 24, 19], [...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."

In [ ]:
idx_max = df_packets_sla.groupby(['Distribution', 'Scenario', 'App_ms', 'Run'])['Total Delay'].idxmax()

df_worst_case = df_packets_sla.loc[idx_max].reset_index(drop=True).copy()

#df_worst_case[df_worst_case['Scenario'] == '2_26_solution_v9'].head(11)
df_worst_case

,Distribution,Scenario,App,Run,Time Step,Object,Id,Status,User,Application,Processing Delay,Propagation Delay,Total Delay,Delay SLAs,Total Path,Hops
0,exponential,1_26_solution_v0,1MMM,run_0,55,DataPacket_1,1.0,finished,1.0,1.0,45.0,24.0,69.0,70.786,"[[13], [13], [13, 21, 16], [16, 22], [22, 16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1,exponential,1_26_solution_v0,1MMM,run_1,18,DataPacket_1,1.0,finished,1.0,1.0,8.0,24.0,32.0,70.786,"[[13], [13], [13, 21, 16], [16, 22], [22, 16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
2,exponential,1_26_solution_v0,1MMM,run_2,33,DataPacket_1,1.0,finished,1.0,1.0,23.0,24.0,47.0,70.786,"[[13], [13], [13, 21, 16], [16, 22], [22, 16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
3,exponential,1_26_solution_v0,1MMM,run_3,32,DataPacket_1,1.0,finished,1.0,1.0,22.0,24.0,46.0,70.786,"[[13], [13], [13, 21, 16], [16, 22], [22, 16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
4,exponential,1_26_solution_v0,1MMM,run_4,27,DataPacket_1,1.0,finished,1.0,1.0,17.0,24.0,41.0,70.786,"[[13], [13], [13, 21, 16], [16, 22], [22, 16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,uniform,2_26_solution_v9,2SMS,run_5,36,DataPacket_1,1.0,finished,1.0,1.0,23.0,32.0,55.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."
656,uniform,2_26_solution_v9,2SMS,run_6,42,DataPacket_1,1.0,finished,1.0,1.0,29.0,32.0,61.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."
657,uniform,2_26_solution_v9,2SMS,run_7,42,DataPacket_1,1.0,finished,1.0,1.0,29.0,32.0,61.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."
658,uniform,2_26_solution_v9,2SMS,run_8,43,DataPacket_1,1.0,finished,1.0,1.0,30.0,32.0,62.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."
659,uniform,2_26_solution_v9,2SMS,run_9,37,DataPacket_1,1.0,finished,1.0,1.0,24.0,32.0,56.0,62.258,"[[24], [24], [24, 21, 16, 12], [12, 16], [16, ...","[{'hop_index': 0, 'link_index': 0, 'source': 2..."

In [ ]:
df_worst_case['SLA_Violation'] = df_worst_case['Total Delay'] > df_worst_case['Delay SLAs']

df_worst_case['SLA_Violation_Percentage'] = (df_worst_case['Total Delay'] - df_worst_case['Delay SLAs']) / df_worst_case['Delay SLAs'] * 100

cols_final = [
    'Distribution', 'Scenario', 'App_ms', 'Run', 
    'Total Delay', 'Delay SLAs', 'SLA_Violation', 'SLA_Violation_Percentage',
    'Processing Delay', 'Propagation Delay', 'Hops'
]

df_worst_case[cols_final].to_pickle("processed_data/dataset_worst_case.pkl")

df_worst_case[cols_final]

,Distribution,Scenario,App,Run,Total Delay,Delay SLAs,SLA_Violation,SLA_Violation_Percentage,Processing Delay,Propagation Delay,Hops
0,exponential,1_26_solution_v0,1MMM,run_0,69.0,70.786,False,-2.523098,45.0,24.0,"[{'hop_index': 0, 'link_index': 0, 'source': 1..."
1,exponential,1_26_solution_v0,1MMM,run_1,32.0,70.786,False,-54.793321,8.0,24.0,"[{'hop_index': 0, 'link_index': 0, 'source': 1..."
2,exponential,1_26_solution_v0,1MMM,run_2,47.0,70.786,False,-33.602690,23.0,24.0,"[{'hop_index': 0, 'link_index': 0, 'source': 1..."
3,exponential,1_26_solution_v0,1MMM,run_3,46.0,70.786,False,-35.015399,22.0,24.0,"[{'hop_index': 0, 'link_index': 0, 'source': 1..."
4,exponential,1_26_solution_v0,1MMM,run_4,41.0,70.786,False,-42.078942,17.0,24.0,"[{'hop_index': 0, 'link_index': 0, 'source': 1..."
...,...,...,...,...,...,...,...,...,...,...,...
655,uniform,2_26_solution_v9,2SMS,run_5,55.0,62.258,False,-11.657940,23.0,32.0,"[{'hop_index': 0, 'link_index': 0, 'source': 2..."
656,uniform,2_26_solution_v9,2SMS,run_6,61.0,62.258,False,-2.020624,29.0,32.0,"[{'hop_index': 0, 'link_index': 0, 'source': 2..."
657,uniform,2_26_solution_v9,2SMS,run_7,61.0,62.258,False,-2.020624,29.0,32.0,"[{'hop_index': 0, 'link_index': 0, 'source': 2..."
658,uniform,2_26_solution_v9,2SMS,run_8,62.0,62.258,False,-0.414405,30.0,32.0,"[{'hop_index': 0, 'link_index': 0, 'source': 2..."
659,uniform,2_26_solution_v9,2SMS,run_9,56.0,62.258,False,-10.051720,24.0,32.0,"[{'hop_index': 0, 'link_index': 0, 'source': 2..."