In [4]:
import pandas as pd

df = pd.read_pickle("processed_data/service_cavia_mean.pkl")
df

,Distribution,Scenario,App_ms,Service_ID,Node_Type,Cavia_Mean,Num_Runs,Empirical_Mean,Empirical_Std,Empirical_Min,Empirical_Max,Abs_Error,Rel_Error_Percent
0,exponential,1_26_solution_v0,1SMM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
1,exponential,1_26_solution_v0,1SMM,1,perception_preprocessing,4.0,100,3.82,3.704706,1,17,0.18,4.500000
2,exponential,1_26_solution_v0,1SMM,2,feature_extraction,4.0,100,3.43,3.065794,1,15,0.57,14.250000
3,exponential,1_26_solution_v0,1SMM,3,context_awareness,10.0,100,10.74,11.658109,1,67,0.74,7.400000
4,exponential,1_26_solution_v0,1SMM,4,avda,9.0,100,10.72,11.162781,1,59,1.72,19.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2179,uniform,2_26_solution_v7,2SMS,5,feature_extraction,4.0,100,3.51,1.105496,2,5,0.49,12.250000
2180,uniform,2_26_solution_v7,2SMS,6,context_awareness,10.0,100,9.25,2.735384,5,14,0.75,7.500000
2181,uniform,2_26_solution_v7,2SMS,7,planning_and_decision,6.0,100,5.96,1.681269,3,8,0.04,0.666667
2182,uniform,2_26_solution_v7,2SMS,8,actuation,4.0,100,3.62,1.152774,2,5,0.38,9.500000
2183,uniform,2_26_solution_v7,2SMS,9,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000

In [5]:
print(f"Total rows: {len(df)}")
print(f"Distributions: {df['Distribution'].nunique()}")
print(f"Scenarios: {df['Scenario'].nunique()}")
print(f"App: {df[['Scenario', 'App_ms']].drop_duplicates().shape[0]}")
print(f"Average percentage error: {df['Rel_Error_Percent'].mean():.2f}")
print(f"Maximum percentage error: {df['Rel_Error_Percent'].max():.2f}")
print(f"Average percentage error per distribution:\n {df.groupby('Distribution')['Rel_Error_Percent'].mean().round(2)}")

Total rows: 2184
Distributions: 6
Scenarios: 10
App: 48
Average percentage error: 6.98
Maximum percentage error: 29.00
Average percentage error per distribution:
 Distribution
exponential           7.40
gamma_k2              6.81
normal                5.95
normal_wide           3.55
normal_wide_trunc    12.55
uniform               5.62
Name: Rel_Error_Percent, dtype: float64

In [6]:
df_exp = df[df['Distribution'] == 'exponential']
df_exp.head(20)

,Distribution,Scenario,App_ms,Service_ID,Node_Type,Cavia_Mean,Num_Runs,Empirical_Mean,Empirical_Std,Empirical_Min,Empirical_Max,Abs_Error,Rel_Error_Percent
0,exponential,1_26_solution_v0,1SMM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
1,exponential,1_26_solution_v0,1SMM,1,perception_preprocessing,4.0,100,3.82,3.704706,1,17,0.18,4.500000
2,exponential,1_26_solution_v0,1SMM,2,feature_extraction,4.0,100,3.43,3.065794,1,15,0.57,14.250000
3,exponential,1_26_solution_v0,1SMM,3,context_awareness,10.0,100,10.74,11.658109,1,67,0.74,7.400000
4,exponential,1_26_solution_v0,1SMM,4,avda,9.0,100,10.72,11.162781,1,59,1.72,19.111111
5,exponential,1_26_solution_v0,1SMM,5,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000
6,exponential,1_26_solution_v0,1SMS,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
7,exponential,1_26_solution_v0,1SMS,1,perception_preprocessing,4.0,100,3.32,2.773904,1,12,0.68,17.000000
8,exponential,1_26_solution_v0,1SMS,2,feature_extraction,4.0,100,3.82,3.704706,1,17,0.18,4.500000
9,exponential,1_26_solution_v0,1SMS,3,context_awareness,10.0,100,8.92,8.047435,1,38,1.08,10.800000
10,exponential,1_26_solution_v0,1SMS,4,planning_and_decision,6.0,100,7.08,7.401447,1,39,1.08,18.000000
11,exponential,1_26_solution_v0,1SMS,5,actuation,4.0,100,4.19,4.493980,1,26,0.19,4.750000
12,exponential,1_26_solution_v0,1SMS,6,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000
13,exponential,1_26_solution_v0,1SSM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
14,exponential,1_26_solution_v0,1SSM,1,perception_preprocessing,4.0,100,3.32,2.773904,1,12,0.68,17.000000
15,exponential,1_26_solution_v0,1SSM,2,feature_extraction,4.0,100,3.82,3.704706,1,17,0.18,4.500000
16,exponential,1_26_solution_v0,1SSM,3,sensor_fusion,6.0,100,6.37,6.894083,1,40,0.37,6.166667
17,exponential,1_26_solution_v0,1SSM,4,map_content,5.0,100,4.31,3.981510,1,19,0.69,13.800000
18,exponential,1_26_solution_v0,1SSM,5,avda,9.0,100,10.72,11.162781,1,59,1.72,19.111111
19,exponential,1_26_solution_v0,1SSM,6,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000